---
EvoChassisEnvironmentTable:
  rpc: get-environment-information
  item: environment-item
  key:
    - name
    - class
  view: ChassisEnvironmentView

ChassisEnvironmentView:
  fields:
    status: status
    temperature: temperature/@celsius

EvoChassisEnvironmentFpcTable:
  rpc: get-environment-fpc-information
  item: environment-component-item
  key:
    - name
    - state
  view: ChassisEnvironmentFpcView

ChassisEnvironmentFpcView:
  fields:
    temperature-readings: _ChassisEnvironmentTempReadingsTable

_ChassisEnvironmentTempReadingsTable:
  item: temperature-reading
  key: temperature-name
  view: _ChassisEnvironmentTempReadingsView

_ChassisEnvironmentTempReadingsView:
  fields:
    temperature: temperature/@celsius

EvoChassisEnvironmentReTable:
  rpc: get-environment-re-information
  item: environment-component-item
  key:
    - name
    - state
  view: ChassisEnvironmentReView

ChassisEnvironmentReView:
  fields:
    temperature-readings: _ChassisEnvironmentTempReadingsTable

EvoChassisEnvironmentPemTable:
  rpc: get-environment-pem-information
  item: environment-component-item
  key:
    - name
    - state
  view: ChassisEnvironmentPemView

ChassisEnvironmentPemView:
  fields:
    temperature-readings: _ChassisEnvironmentPemTempReadingsTable

_ChassisEnvironmentPemTempReadingsTable:
  item: psm-information/temperature-reading
  key: temperature-name
  view: _ChassisEnvironmentTempReadingsView
